#!/usr/bin/env bash
help(){
	gnostr-git reflog -h | sed -e "s/git/gnostr-git/g"
	printf "   or: gnostr-git reflog [--hash-list] [-hl]\n"
	printf "   or: gnostr-git reflog [--format] [-f]\n"
	printf "   or: gnostr-git reflog [-gd]\n"
	printf "   "
	printf "   \n"
	printf "    gnostr-git reflog accepts any of the options accepted by gnostr-git log\n"
	echo "  try:"
	echo "       gnostr-git log    --format='%C(auto)%H%<|(17)%gd/commit:%s'"
	echo "       gnostr-git reflog --format='%C(auto)%H%<|(17)%gd/commit:%s'"
	exit
}
for ((i=1; i<=$#; i++)); do
if
[[ ${!i} == "--hash-list" ]] || [[ ${!i} == "-hl" ]]; then
	gnostr-git reflog show --format='%C(auto)%H'
	exit
elif
[[ ${!i} == "--format" ]] || [[ ${!i} == "-f" ]]; then
	gnostr-git reflog show --format='%C(auto)%H/%<|(17)%gd/commit:%s'
	exit
elif
[[ ${!i} == "-gd" ]]; then
	gnostr-git reflog show --format='%C(auto)%H/%<|(17)%gd'
	exit
elif [[ ${!i} == *"help" ]] || [[ ${!i} == "-h" ]]; then
	help
	exit
else
	((i++))
	gnostr-git-reflog --format ${!i}
	exit
fi
done