#!/usr/bin/env bash

GNOSTR_GIT=$(which gnostr-git)
GNOSTR_WEEBLE=$(which gnostr-weeble)
GNOSTR_WOBBLE=$(which gnostr-wobble)
GNOSTR_BLOCKHEIGHT=$(which gnostr-blockheight)

#git using sha1
$GNOSTR_GIT \
diff \
4b825dc642cb6eb9a060e54bf8d69288fbee4904 \
HEAD \
> \
gnostr-snapshot-$GNOSTR_WEEBLE/$GNOSTR_WOBBLE/$GNOSTR_BLOCKHEIGHT.patch

exit;

#git using sha256
$GNOSTR_GIT \
diff \
6ef19b41225c5369f1c104d45d8d85efa9b057b53b14b4b9b939dd74decc5321 \
HEAD \
> \
gnostr-snapshot-$GNOSTR_WEEBLE/$GNOSTR_WOBBLE/$GNOSTR_BLOCKHEIGHT.patch
