#!/usr/bin/env bash
gnostr_relays=${GNOSTR_RELAYS:-$(gnostr git config gnostr.relays)}
export gnostr_relays
gnostr_relayer=${GNOSTR_RELAYER:-$(which gnostr-cat)}
export gnostr_relayer
#to_stdout=0
#echo ${!#}
echo $0 $1
if [[ $1 = "-c" ]]; then
curl_test(){
echo "curl test"
	curl --include \
     --no-buffer \
     --header "Connection: Upgrade" \
     --header "Upgrade: websocket" \
     --header "Host: example.com:80" \
     --header "Origin: http://example.com:80" \
     --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
     --header "Sec-WebSocket-Version: 13" \
     http://example.com:80/
 }
curl_test
exit;
fi

if [[ $1 = "-t" ]]; then
gnostr_tests(){
GNOSTR=$(which gnostr)
echo "$GNOSTR tests"
echo "$GNOSTR test 1"
$GNOSTR --sec $(gnostr --hash 0) --envelope --content "test 1"
echo "$GNOSTR test 2"
$GNOSTR --sec $(gnostr --hash 0) --envelope --content "test 2" | $(which gnostr-cat) -u wss://relay.damus.io

GNOSTR_QUERY=$(which gnostr-query)
echo "$GNOSTR_QUERY tests"
echo "$GNOSTR_QUERY test 1"
$GNOSTR_QUERY -i 184ba32823ecb0e38d195c6484aace10edb7a4948c5e52434a8833e115c3e5f6 | gnostr-cat -u wss://relay.damus.io
echo "$GNOSTR_QUERY test 2"
$GNOSTR_QUERY -i 184ba32823ecb0e38d195c6484aace10edb7a4948c5e52434a8833e115c3e5f6 #| $gnostr_relayer $gnostr_relay
}
gnostr_tests
exit;
fi

if ! command -v $gnostr_relayer; then
	printf "gnostr-cat '%s' not found. Please install or set GNOSTR_RELAYER to your preferred relayer.\n" "$gnostr_relayer"
	exit 1
fi

if [ "$gnostr_relays" == "" ]; then
	printf 'no relays set. set\n\n    export GNOSTR_RELAYS="wss://relay.damus.io wss://relay.gnostr.org" or\n\n    gnostr-git config --global --add gnostr.relays "wss://relay.damus.io wss://relay.gnostr.org"\n' >&2
	exit 1
fi

#echo $gnostr_relayer $gnostr_relays
$gnostr_relayer $gnostr_relays
