#!/usr/bin/env bash
#
GNOSTR=$(which gnostr)

# Create a data URL from a file
(\
	local mimeType=$(file -b --mime-type "$1") 2>/tmp/gnostr-dataurl; \
	[[ $mimeType == text/* ]] && mimeType="${mimeType};charset=utf-8"; \
	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')"; \
)
