#!/usr/bin/env bash
#

GNOSTR=$(which gnostr)

function gnostr-install-depends(){

    if [[ "$OSTYPE" == "linux-gnu" ]]; then

        if hash apt 2>/dev/null; then

            apt -y install autoconf build-essential          \
                libtool autotools-dev automake               \
                bsdmainutils                                 \
                groff                                        \
                pkg-config python3                           \
                libboost libqrencode libevent-dev            \
                libboost-system-dev libboost-filesystem-dev  \
                libboost-test-dev libboost-thread-dev        \
                libminiupnpc-dev libzmq3-dev libqrencode-dev \
                linuxbrew-wrapper                            \
                wget
        fi

    elif [[ "$OSTYPE" == "darwin"* ]]; then

        if hash brew 2>/dev/null; then

            brew install autoconf automake                   \
                curlpp                                       \
                groff                                        \
                libevent librsvg libtool                     \
                miniupnpc                                    \
                pkg-config python                            \
                qrencode                                     \
                wget
        else

            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
            gnostr-install-depends
        fi
    fi
}
gnostr-install-depends
