#!/usr/bin/env bash
#

GNOSTR=$(which gnostr)

# Determine size of a file or total size of a directory
function gnostr-fs() {
	if du -b /dev/null > /dev/null 2>&1; then
		local arg=-sbh;
	else
		local arg=-sh;
	fi
	if [[ -n "$@" ]]; then
		du $arg -- "$@";
	else
		du $arg .[^.]* ./*;
	fi;
}
if [[ $1 == "-h" ]] || [[ $1 == "--help" ]];
then
    man du | sed 's/du/gnostr-du/g';
    man df | sed 's/df/gnostr-df/g';
    exit;
fi
gnostr-fs
