#!/usr/bin/env bash

mkdir -p .gnostr

GNOSTR_GIT=$(which gnostr-git)
declare WEEBLE
WEEBLE=$(gnostr-weeble)
## echo $WEEBLE
declare WOBBLE
WOBBLE=$(gnostr-wobble)
## echo $WOBBLE
declare BLOCKHEIGHT
BLOCKHEIGHT=$(gnostr-blockheight)
## echo $BLOCKHEIGHT

declare REPO
REPO=$(pwd | grep -o '[^/]*$')
## echo $REPO
declare BRANCH
BRANCH=$(echo $(git branch --show-current) | sed -e 's/\//-/g')
## echo $BRANCH
declare UTC_SECS
UTC_SECS=$(date +%s)
## echo $UTC_SECS

declare REMOTE_PATH
REMOTE_PATH=$REPO-$WEEBLE-$WOBBLE-$BLOCKHEIGHT-$BRANCH
## echo $REMOTE_PATH

help(){
	printf "   gnostr-snapshot --help     [-h]     print help\n"
	printf "   gnostr-snapshot --depth    [-d]     depth\n"
	printf "   "
	exit
}

#git using sha1
default(){
touch $REMOTE_PATH.patch
$GNOSTR_GIT diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 HEAD > $REMOTE_PATH.patch
exit;
}

#git using sha256
sha256(){
touch gnostr-snapshot-$REMOTE_PATH.patch
$GNOSTR_GIT diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 HEAD > gnostr-snapshot-$REMOTE_PATH.patch
exit;
}

for ((i=1; i<=$#; i++)); do

  ## echo "i=${!i}"

  if [[ ${!i} == "-h" ]] || [[ $1 == "--help" ]] || [[ $1 == "help" ]]; then
    help
    exit
  fi

  if [[ ${!i} == "-d" ]] || [[ $1 == "--depth" ]] || [[ $1 == "depth" ]]; then
  ((i++))
    if [[ ${!i} =~ ^[0-9]+$ ]]; then
      declare DEPTH
      DEPTH=${!i}
       ## echo "${!i} is a number"
       ## echo DEPTH=$DEPTH
      ((i++))
    else
       echo "${!i} is not a number"
       help
    fi
  fi

done
default
