name: gnostr-docker

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        tag: ["latest", "slim-bullseye"]
    runs-on: ${{ matrix.os }}
    container: rust:${{ matrix.tag }}

    steps:
      - run: apt-get update && apt-get install autoconf build-essential curl cmake jq libexpat1-dev libcurl4-openssl-dev libssl-dev libtool lsb-release   git make nodejs npm pkg-config python3 python-is-python3 sudo tcl zlib1g-dev -y
      ## notice: this is a pre checkout step
      ## notice: additional operations can be done prior to checkout
      ## - run: apk update && apk add bash cmake git python3 && python3 -m ensurepip
      - run: printenv
      - name: checkout@v3 fetch-depth submodules set-safe-dir true
        uses: actions/checkout@v3
        with:
          fetch-depth: '100'
          submodules: 'true'
          set-safe-directory: 'true'
      ## notice: these are post checkout steps
      ## - run: apk update && apk add autoconf automake build-base openssl-dev libtool make
      - run: touch ~/GITHUB_TOKEN.txt
      - run: git config --global --add safe.directory /__w/gnostr/gnostr || true
      - run: make detect
      - run: ./build.cmake.sh
      - run: cmake .
      - run: make
      - run: V=1 make gnostr bins gnostr-sha256 &&  gnostr --sec $(gnostr-sha256) --content 'gnostr is already a fully functioning command line utility...'  | gnostr-post-event wss://nos.lol
      - run: make nvm
      - run: make bins
      - run: make      tui
      - run: make gnostr-act
      - run: make gnostr-cat
      - run: make gnostr-cli
      - run: make gnostr-command
      - run: make gnostr-git
      - run: make gnostr-grep
      - run: make gnostr-legit
      - run: make gnostr-proxy
      - run: make gnostr-sha256
      - run: make libsecp256k1.a
      - run: make                 gnostr-all
      - run: make                     gnostr-install
      - run: make                         all
      - run: make                            install
      - run: ls /usr/local/bin
      - run: gnostr --sec $(gnostr-sha256) --content "$(gnostr-git show HEAD)" | gnostr-post-event wss://relay.damus.io
