name: ubuntu-matrix

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ !env.ACT }}
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          set-safe-directory: 'true'
      - name: Restore deps
        id: cache-deps-restore
        uses: actions/cache/restore@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            deps/jq
            deps/git
            deps/secp256k1
            deps/hyper-sdk
            deps/hyper-nostr
            /root/.cargo
            /root/.rustup
          key: ${{ runner.os }}-deps

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: rustup
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 make autoconf automake libtool build-essential tclsh gettext libcurl4-openssl-dev bash util-linux
          touch ~/GITHUB_TOKEN.txt

      - name: sudo make libsecp256k1.a
        run: |
          sudo make libsecp256k1.a

      - name: make gnostr
        run: |
          make gnostr

      - name: Save deps
        id: cache-deps-save
        uses: actions/cache/save@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            deps/jq
            deps/git
            deps/secp256k1
            deps/hyper-sdk
            deps/hyper-nostr
            /root/.cargo
            /root/.rustup
          key: ${{ steps.cache-deps-restore.outputs.cache-primary-key }}

