name: ubuntu-matrix

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ !env.ACT }}
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'recursive'
          set-safe-directory: 'true'
      - name: Restore deps
        id: cache-deps-restore
        uses: actions/cache/restore@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            nostcat
            deps/*/**.a
            libjq.a
            libgit.a
            libtclstub.a
            libsecp256k1.a
            deps/jq/libjq.a
            deps/git/libgit.a
            deps/tcl/unix/libtclstub.a
            deps/secp256k1/.libs/libsecp256k1.a
            deps/jq/modules/oniguruma/src/.libs/libsecp256k1.a
            deps/nostcat/target/release/nostcat
          key: ${{ runner.os }}-deps

      - name: apt-get update and install
        run: |
          printenv
          apt-get update && apt-get install -y python3 make autoconf automake libtool build-essential tclsh gettext libcurl4-gnutls-dev
          touch ~/GH_ACT_TOKEN.txt
      - name: make submodules
        run: |
          echo
          #make submodules
      #- name: make act-install
      #  run: |
      #    make act-install
      - name: make gnostr
        run: |
          sudo make install
      - name: Save deps
        id: cache-deps-save
        uses: actions/cache/save@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            nostcat
            deps/*/**.a
            libjq.a
            libgit.a
            libtclstub.a
            libsecp256k1.a
            deps/jq/libjq.a
            deps/git/libgit.a
            deps/tcl/unix/libtclstub.a
            deps/secp256k1/.libs/libsecp256k1.a
            deps/jq/modules/oniguruma/src/.libs/libsecp256k1.a
            deps/nostcat/target/release/nostcat
          key: ${{ steps.cache-deps-restore.outputs.cache-primary-key }}

